name: Create RAID WW2 mod release
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest #windows-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@main
    #- name: Delete Existing Release
      # see https://github.com/ame-yu/action-delete-latest-release?tab=readme-ov-file
      # and see https://github.com/actions/github-script
      #uses: actions/github-script@v4
      #with:
        #github-token: ${{secrets.GITHUB_TOKEN}}
        #script: |
          #const { owner, repo } = context.repo
          #const { data: { id } } = await github.repos.getLatestRelease({ owner, repo })
          #await github.repos.deleteRelease({ owner, repo, release_id: id })

    - name: Archive Mod
      # https://github.com/marketplace/actions/action-zip
      uses: montudor/action-zip@v1
      with:
        args: zip -qq -r .\RAID-DynamicLocalization.zip . -i .\RAID-DynamicLocalization
    #- name: Archive Mod
      #run: |
         #.\.github\7za.exe -tzip a ".\RAID-DynamicLocalization.zip" ".\RAID-DynamicLocalization"
      #shell: powershell

    - name: Get XML info
      # see https://github.com/marketplace/actions/get-xml-info
      id: getxml
      uses: mavrosxristoforos/get-xml-info@2.0
      with:
        xml-file: './RAID-DynamicLocalization/supermod.xml'
        xpath: '//mod/@version'

    - name: render meta.json
      id: render
      # https://github.com/marketplace/actions/json-templater
      uses: georgepstaylor/render-json-template@v0.0.13
      with:
        json-file-path: .\.github\meta.json
        output-file-name: meta.json
        field-value-pairs: |
          $[0][version]: ${{ steps.getxml.outputs.info }}
    - run: |
        cat ${{ steps.render.outputs.rendered-json-file }}

    #- name: Create meta.json
      #id: create_meta_file
      #run: |
        #$(cat .\.github\meta.json) > ./meta.json

    #- name: Update meta.json
      #id: update_meta
      # https://github.com/marketplace/actions/set-json-field
      #uses: jossef/action-set-json-field@v2.1
      #with:
        #file: meta.json
        #field: version
        #value: ${{ steps.getxml.outputs.info }}

    - name: GH Release
      # https://github.com/marketplace/actions/gh-release
      # You may pin to the exact commit or the version.
      # uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda
      id: upload-release-asset 
      uses: softprops/action-gh-release@v2.2.1
      with:
        # Note-worthy description of changes in release
        body: |
          This release zip is automatically updated on every push. You can ignore the "x commits behind" message.
        # Path to load note-worthy description of changes in release from
        body_path: CHANGELOG.md
        # Gives the release a custom name. Defaults to tag name
        name: Release ${{ steps.getxml.outputs.info }}
        # Gives a tag name. Defaults to github.GITHUB_REF
        tag_name: ${{ steps.getxml.outputs.info }}
        # Newline-delimited list of path globs for asset files to upload
        files: |
          RAID-DynamicLocalization.zip
          meta.json
        # Specifies whether this release should be set as the latest release for the repository. Drafts and prereleases cannot be set as latest. Can be `true`, `false`, or `legacy`. Uses GitHub api default if not provided
        make_latest: legacy
  
